language: node_js
node_js: stable
branchs:
  only:
  - master
install:
- npm install
script:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_c26c748b506a_key -iv $encrypted_c26c748b506a_iv
  -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh pi@pi.toannhu.com -o StrictHostKeyChecking=no 'cd ~/Projects && git pull && npm install && npm run deploy'
