language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_c26c748b506a_key -iv $encrypted_c26c748b506a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
   branch: master
